# Site wide configuration

title: Welcome to Amon's website
locale: en_US
description: Where everything starts.
logo: site-logo.png
search: false
url: http://localhost:4000

# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..2
  use_coderay: false

mathjax: true

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md", "vendor"]


# Site owner
owner:
  name: Amon M. R. BAZONGO
  avatar: bio-photo.png
  email: amonmoce@gmail.com
  disqus-shortname:
  twitter: amonmoce #username
  facebook: amonmoce #username
  github: amonmoce #username
  stackexchange: #http://stackoverflow.com/users/123456/username
  linkedin: #username
  instagram: #username
  flickr: #username
  tumblr: #username
  pinterest: #username
  weibo: #userid
  google:
    plus: amonmoce #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
